apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: opaque
stringData:
    admin-password: ENC[AES256_GCM,data:oyqhVT/JuFJXxi/7IBBwbHGW,iv:/m7zb4ytLAUaMK29lyyt3WVDhu41Vh9TXo9oc7B3r+s=,tag:ZuDmzw+PEUpdcN+3sVC9rA==,type:str]
sops:
    age:
        - recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWVV1SitKVkJCVVNObVFE
            dml6S3cvQ1dEczRiQjZudmJSNEsyQ2d0OUFzCklwWTFYQjRPRnlDSFBjOEIvRlox
            ajFLdDdxUmhCVnQ3Wm1ST0twNzJWdFEKLS0tIFJMYmpqRnhaU1dvc1pFQUtkdFJi
            eGVvd21jV0xvSCsrUXA3SThQVW1EbXMKA/Jgu1aoXdL81bi9Ll6Dp3Itjfh7X2Fx
            z1Z99CMVh1ynOaWVrC1m9FrwT+avmHZ7cl8bTcGFwnki/VQfxR1O3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T04:45:21Z"
    mac: ENC[AES256_GCM,data:68y8POfvjwDOenty0Q9YcjzOyvY+2cCDafRXMZQhlu+QRf/h4dukZNedo+7ud4Agr4Z9MIJtJO6WkaVwqwQZWDBjIdBxtcAjaySrHTJzP1Kyc8GyQGBzbcQ7jWoE+6SsCyoSk5AZvWzRGcof0JFq/HsD07qvYp13DerwNwHzgmI=,iv:uimvOUkVEqffG91o2etw/isK6rjkZO8bVAsoYpmYTgk=,tag:SG7g6jfW+g2QJENmOI5JGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
