apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: opaque
stringData:
    admin-user: ENC[AES256_GCM,data:w5gqiFs=,iv:GmFsPz37dLYDg1b+3wzRC3bSM2HNUHmM4miv3kdM24Q=,tag:64ifrFHzfXZ6YIpif5ay2A==,type:str]
    admin-password: ENC[AES256_GCM,data:A/utEfQUvUx1TkeI5JeYqh1W,iv:t4VOZ7lNfavbYMEXd4o4R4N+jyGdfxRWRh6kzG9CXoU=,tag:0AWhAO0desNTvCB5wnIdXQ==,type:str]
sops:
    age:
        - recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aituNHRyN1VaQk9YWkFH
            VWI3aXN6NENrOEJkMW5XRm9JZzdTR01vTlgwCmhOdmpHRVJqZldaZ0ZVckNBM0pi
            cTNvN1JrOE93RjFXUzFCTEx6TW91NXMKLS0tIFlHVGZBOC90ZFNOd3BzTlRINElL
            dWFhTGpjVDNnajUwanRnWm9manRsSlUKW79wXLNyl7ukjVCqJSn4hAE2gOKtzRMN
            ahqFWuhyHmOmXdI7k4VdARCFsHICmJVPDHOHxKvMwW1DWr//gduuWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T04:58:06Z"
    mac: ENC[AES256_GCM,data:QsroRcsZjEiTZURkkg3ThbMFy95pGnd5GfumgM4P1zMZH5jwsov9+O551Dl3Q5h17JvKLvKZ8P/UVaNVW05Rj/GsMYXTtvx/X84JlXiCSh0HdxVfUExA+YUA8V4FdqlgjMDidHv8xULMLsn4GusUZ2e1n2leAl0iO/57W2J4iK8=,iv:asAkhSad7s8HDobk4s1135vfC8h4ixOS58/OyBri++s=,tag:VEd5kHYpM/ii7dEL8f5xkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
